import React from 'react';

// This component is rendered hidden from view but used for PDF generation
const PartyReceipt = React.forwardRef(({ people, calculatedResults, totalAmount, date }, ref) => {
    return (
        <div ref={ref} className="w-[800px] bg-[#000000] p-10 text-white font-sans relative overflow-hidden" style={{ minHeight: '1000px' }}>
            {/* Header */}
            <div className="text-center mb-12 border-b border-[#3A3A3C] pb-8 pt-4">
                <h1 className="text-5xl font-bold tracking-tight text-white mb-3">
                    RECEIPT
                </h1>
                <p className="text-[#8E8E93] text-xl font-medium tracking-wide">{date}</p>
                <div className="flex justify-center mt-5 space-x-3 text-2xl opacity-80">
                    <span></span><span className="text-[#8E8E93] text-xl px-2">Lunch Share</span>
                </div>
            </div>

            {/* Content */}
            <div className="space-y-4">
                {Object.values(calculatedResults).map((result, index) => (
                    <div
                        key={result.name}
                        className={`p-6 rounded-2xl ${result.treatReceived > 0 ? 'bg-[#1C1C1E] border border-[#FF9F0A]/30' : 'bg-[#1C1C1E]'}`}
                    >
                        <div className="flex justify-between items-center mb-5 border-b border-[#3A3A3C] pb-4">
                            <h2 className="text-2xl font-bold flex items-center text-white">
                                {result.name}
                                {result.treatReceived > 0 && <span className="ml-3 text-[13px] bg-[#FF9F0A]/20 text-[#FF9F0A] px-2.5 py-1 rounded-full font-semibold uppercase tracking-wider">Treated</span>}
                            </h2>
                            <div className="text-right flex items-center">
                                {result.treatReceived > 0 && (
                                    <span className="text-xl font-bold text-[#8E8E93] line-through mr-3">
                                        ฿{result.subtotalBeforeProportion.toFixed(0)}
                                    </span>
                                )}
                                <span className={`text-3xl font-bold ${result.treatReceived > 0 ? 'text-[#FF9F0A]' : 'text-white'}`}>
                                    {result.treatReceived > 0 ? 'FREE' : `฿${result.totalPay.toFixed(2)}`}
                                </span>
                            </div>
                        </div>

                        {/* Details List */}
                        <div className="grid grid-cols-2 gap-4 text-[#8E8E93] text-[17px]">
                            <div className="space-y-2">
                                <p className="flex justify-between pr-4"><span>Order Subtotal</span> <span className="text-[#EBEBF5]">฿{result.individualSubtotal.toFixed(2)}</span></p>
                                <p className="flex justify-between pr-4"><span>Shared Items</span> <span className="text-[#EBEBF5]">฿{result.sharedItemContribution.toFixed(2)}</span></p>
                            </div>
                            <div className="space-y-2 text-right">
                                {result.proportionalShipping > 0 && <p className="flex justify-between pl-4"><span>Shipping</span> <span className="text-[#EBEBF5]">+฿{result.proportionalShipping.toFixed(2)}</span></p>}
                                {result.proportionalDiscount > 0 && <p className="flex justify-between pl-4 text-[#FF453A]"><span>Discount</span> <span>-฿{result.proportionalDiscount.toFixed(2)}</span></p>}
                                {result.treatContribution > 0 && (
                                    <p className="flex justify-between pl-4 text-[#FF9F0A] font-medium"><span>Treat Contribution</span> <span>+฿{result.treatContribution.toFixed(2)}</span></p>
                                )}
                            </div>
                        </div>

                        {(result.proportionalServiceCharge > 0 || result.proportionalVat > 0) && (
                            <div className="mt-4 pt-4 border-t border-[#3A3A3C] text-[15px] text-[#8E8E93] flex justify-end gap-6">
                                {result.proportionalServiceCharge > 0 && <span>SC: ฿{result.proportionalServiceCharge.toFixed(2)}</span>}
                                {result.proportionalVat > 0 && <span>VAT: ฿{result.proportionalVat.toFixed(2)}</span>}
                            </div>
                        )}
                    </div>
                ))}
            </div>

            {/* Grand Total Footer */}
            <div className="mt-12 border-t border-[#3A3A3C] pt-8 flex justify-between items-end">
                <div className="text-[#8E8E93] text-lg font-medium leading-relaxed">
                    Thank you for dining together.<br />
                    Generated by Lunch Share App.
                </div>
                <div className="text-right">
                    <p className="text-xl text-[#8E8E93] font-semibold mb-2 tracking-widest uppercase">Total Amount</p>
                    <p className="text-7xl font-semibold text-white tracking-tight">
                        ฿{totalAmount.toFixed(2)}
                    </p>
                </div>
            </div>
        </div>
    );
});

export default PartyReceipt;
